package config

// Static form-option data mirrored from the reference Laravel configs. These
// are hardcoded there (not env-driven), so they live here as Go literals.

// careerConfig mirrors reference/config/career.php.
func careerConfig() Career {
	return Career{
		EmploymentTypes: []Option{
			{"full_time", "Full-Time"},
			{"part_time", "Part-Time"},
			{"contract", "Contract"},
			{"freelance", "Freelance"},
			{"internship", "Internship"},
		},
	}
}

// membershipConfig mirrors reference/config/membership.php.
func membershipConfig() Membership {
	return Membership{
		Currency:         getenv("MEMBERSHIP_CURRENCY", "BDT"),
		GateableFeatures: []string{"members", "posts"},
		ExpiryEnabled:    true,
		ExpiryAt:         "00:30",
		ProofMaxKB:       2048,
		ProofMimes:       []string{"jpg", "jpeg", "png", "pdf"},
	}
}

// localNames mirrors reference/config/app.php 'local_names'.
func localNames() []LocalName {
	return []LocalName{
		{Code: "bn", Label: "বাংলা নাম", Required: true},
	}
}

// educationConfig mirrors reference/config/education.php.
func educationConfig() Education {
	return Education{
		Levels: []string{"Honors", "Masters", "PhD", "Diploma", "Certificate"},
		Institutions: []string{
			"Khulna University",
			"Bangabandhu Sheikh Mujib Medical University (BSMMU)",
			"Bangabandhu Sheikh Mujibur Rahman Agricultural University",
			"Bangabandhu Sheikh Mujibur Rahman Digital University",
			"Bangabandhu Sheikh Mujibur Rahman Maritime University",
			"Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
			"Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj",
			"Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University",
			"Bangladesh Agricultural University",
			"Bangladesh Open University",
			"Bangladesh University of Engineering and Technology (BUET)",
			"Bangladesh University of Professionals (BUP)",
			"Bangladesh University of Textiles",
			"Barishal University",
			"Begum Rokeya University, Rangpur",
			"Chittagong University of Engineering & Technology (CUET)",
			"Comilla University",
			"Dhaka University of Engineering & Technology (DUET)",
			"Gopalganj Science and Technology University",
			"Hajee Mohammad Danesh Science and Technology University",
			"Islamic Arabic University",
			"Islamic University, Kushtia",
			"Jagannath University",
			"Jahangirnagar University",
			"Jashore University of Science and Technology",
			"Jatiya Kabi Kazi Nazrul Islam University",
			"Khulna University of Engineering & Technology (KUET)",
			"Khulna Agricultural University",
			"Kurigram Agricultural University",
			"Military Institute of Science and Technology (MIST)",
			"National University",
			"Noakhali Science and Technology University",
			"Pabna University of Science and Technology",
			"Patuakhali Science and Technology University",
			"Rabindra University, Bangladesh",
			"Rajshahi University of Engineering & Technology (RUET)",
			"Shahjalal University of Science and Technology",
			"Sheikh Hasina University",
			"Sher-e-Bangla Agricultural University",
			"Sylhet Agricultural University",
			"Chittagong University",
			"Dhaka University",
			"Rajshahi University",
		},
		Subjects: []string{
			"Bangla",
			"Accounting",
			"Agronomy",
			"Agroforestry",
			"Anthropology",
			"Arabic",
			"Architecture",
			"Banking and Insurance",
			"Biochemistry",
			"Biomedical Engineering",
			"Biotechnology",
			"Botany",
			"Chemical Engineering",
			"Chemistry",
			"Civil Engineering",
			"Computer Science and Engineering",
			"Criminology",
			"Data Science",
			"Dentistry (BDS)",
			"Development Studies",
			"Drawing and Painting",
			"Economics",
			"Education",
			"Electrical and Electronic Engineering",
			"Electronics and Communication Engineering",
			"English",
			"Entomology",
			"Environmental Science",
			"Finance",
			"Fine Arts",
			"Fisheries",
			"Food Engineering",
			"Food Science and Technology",
			"Forensic Science",
			"Gender and Development Studies",
			"Genetic Engineering and Biotechnology",
			"Geography and Environment",
			"Geology",
			"Graphic Design",
			"History",
			"Horticulture",
			"Human Resource Management",
			"Industrial and Production Engineering",
			"Information Technology",
			"International Relations",
			"Islamic History and Culture",
			"Islamic Studies",
			"Law (LL.B)",
			"Linguistics",
			"Management",
			"Marketing",
			"Mass Communication and Journalism",
			"Materials Science and Engineering",
			"Mathematics",
			"Mechanical Engineering",
			"Mechatronics Engineering",
			"Medicine (MBBS)",
			"Microbiology",
			"Molecular Biology",
			"Music",
			"Naval Architecture and Marine Engineering",
			"Nursing",
			"Nutrition and Food Science",
			"Oceanography",
			"Peace and Conflict Studies",
			"Petroleum and Mining Engineering",
			"Pharmacy",
			"Philosophy",
			"Physical Education",
			"Physics",
			"Plant Pathology",
			"Political Science",
			"Population Sciences",
			"Psychology",
			"Public Administration",
			"Public Health",
			"Poultry Science",
			"Robotics and Mechatronics Engineering",
			"Sanskrit",
			"Sociology",
			"Software Engineering",
			"Soil Science",
			"Statistics",
			"Textile Engineering",
			"Theater and Performance Studies",
			"Tourism and Hospitality Management",
			"Urban and Regional Planning",
			"Women and Gender Studies",
			"Zoology",
		},
	}
}
